# Generated by Django 4.2.9 on 2024-01-26 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('qtype', models.CharField(choices=[('MCQ', 'Multiple Choice Question (MCQ)'), ('CODING', 'Coding'), ('SUBJECTIVE', 'Subjective')], max_length=10)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
            ],
        ),
    ]
