# Generated by Django 4.2.9 on 2024-01-27 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjective',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('statement', models.TextField()),
                ('setters_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
            ],
        ),
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('qno', models.IntegerField()),
                ('question_text', models.TextField()),
                ('optionA', models.TextField()),
                ('optionB', models.TextField()),
                ('optionC', models.TextField()),
                ('optionD', models.TextField()),
                ('correct_option', models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd')], max_length=2)),
                ('settersid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
            ],
        ),
    ]
