# Generated by Django 4.2.9 on 2024-01-30 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_registereduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='McqSubmisstion',
            fields=[
                ('subid', models.AutoField(primary_key=True, serialize=False)),
                ('marked_option', models.CharField(max_length=2)),
                ('ques_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mcq')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'test_id', 'ques_id')},
            },
        ),
    ]
