# Generated by Django 4.2.9 on 2024-01-30 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_mcqsubmisstion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='McqSubmisstion',
            new_name='McqSubmission',
        ),
    ]
